// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $countries_name_ from "./routes/countries/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Busqueda from "./islands/Busqueda.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/countries/[name].tsx": $countries_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Busqueda.tsx": $Busqueda,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
